name: back3

on:
  push:
    branches: [ back3 ]

jobs:
  sync-and-deploy-on-back:
    runs-on: ubuntu-latest

    env:
      NCLOUD_REPO_URL: https://contest22:${{ secrets.NCLOUD_TOKEN }}@devtools.ncloud.com/3067145/greenaccounter.git
      NCR_REGISTRY: greenaccounter.kr.ncr.ntruss.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set YAML file path based on branch
        id: set_path
        run: |
          echo "[DEBUG] Setting YAML file path based on branch: ${GITHUB_REF_NAME}"
          if [[ "${GITHUB_REF_NAME}" == "back3" ]]; then
            echo "YAML_PATH=back.yaml" >> $GITHUB_ENV
            echo "[DEBUG] YAML_PATH set to back.yaml"
          else
            echo "[DEBUG] Branch name is not 'back', skipping YAML path setting"
          fi

      - name: Push YAML file to Ncloud Source Commit
        run: |
          echo "[DEBUG] Configuring git user"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          echo "[DEBUG] Creating ncloud-deploy directory and copying YAML file"
          mkdir -p ncloud-deploy
          cp "${{ env.YAML_PATH }}" ncloud-deploy/back.yaml
          cd ncloud-deploy
          
          echo "[DEBUG] Initializing git repository"
          git init
          git checkout -b $GITHUB_REF_NAME  # Set the initial branch to match the GitHub branch name
          git remote add origin $NCLOUD_REPO_URL

          echo "[DEBUG] Fetching latest changes from remote branch $GITHUB_REF_NAME"
          git fetch origin $GITHUB_REF_NAME || echo "[DEBUG] Branch $GITHUB_REF_NAME does not exist remotely, creating new branch"

          echo "[DEBUG] Resetting repository to remote branch $GITHUB_REF_NAME"
          git checkout -B $GITHUB_REF_NAME || git checkout -b $GITHUB_REF_NAME

          echo "[DEBUG] Adding new or updated back.yaml"
          git add back.yaml
          
          if git diff --cached --quiet; then
            echo "[DEBUG] No changes to commit"
          else
            echo "[DEBUG] Committing changes"
            git commit -m "Deploy YAML file from GitHub branch $GITHUB_REF_NAME"
            echo "[DEBUG] Pushing changes to remote branch $GITHUB_REF_NAME"
            git push origin HEAD:refs/heads/$GITHUB_REF_NAME --force  # Use --force to overwrite if necessary
          fi

      - name: Log in to Ncloud Container Registry
        run: |
          echo "[DEBUG] Logging in to Ncloud Container Registry"
          echo "${{ secrets.NCR_PASSWORD }}" | docker login -u ${{ secrets.NCR_USERNAME }} --password-stdin $NCR_REGISTRY

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="$NCR_REGISTRY/${GITHUB_REF_NAME}:latest"
          echo "[DEBUG] Building Docker image: $IMAGE_NAME"
          docker build -t $IMAGE_NAME -f Dockerfile .  # Ensure Dockerfile is in the root or adjust path if needed
          echo "[DEBUG] Pushing Docker image: $IMAGE_NAME"
          docker push $IMAGE_NAME
